### ISSUE TITLE
How to set the canvas's position as (0,0)

### ISSUE THREAD

**Issue by ketoo** [Nelarius/imnodes#2] opened 2019-11-24 03:04 UTC
Hi,
I'd like to integrate this library as a part of my blueprint framework as it looks simple and easy to use. In the blueprint design window, I'd like to let the user reset the position of the canvas if we have many nodes on the canvas and do not know where are we now.

I didn't found the function via the source code, may I know how to do that?

Thanks

**Comment by Nelarius** [comment] 2019-11-25 08:59
Are you talking about resetting the offset caused by panning around the canvas with the middle mouse button? There unfortunately isn't any way to do that via `imnodes.h` at the moment, but a reset function could be added pretty easily! In essence, the `EditorContext::panning` field will have to be set to zero.

**Comment by ketoo** [comment] 2019-11-26 08:47
Hi Nelarius,

Thanks for your help, I modified the code and it works!
I have done a PR and hope it can be merged into your repo as this interface is really useful for the developer when they want to do more features.

**Comment by Nelarius** [comment] 2019-11-26 17:09
Merged #4 🙂

**Closed by Nelarius** 2019-11-26 17:09 UTC
